/* CRIANDO UM BANCO DE DADOS */
CREATE DATABASE nomebancodados;

/* APAGANDO UM BANCO DE DADOS */
DROP DATABASE nomebancodados;

/* ACESSANDO O BANCO DE DADOS CRIADO */
\c nomebancodados

/* CRIANDO UMA TABELA DE DADOS */
CREATE TABLE nometabela(
    info TEXT,
    info2 INT,
);

/* APAGANDO UMA TABELA DE DADOS */
DROP TABLE nometabela;

/* PROPRIEDADES DAS COLUNAS */
PRIMARY KEY,
NOT NULL,
AUTO_INCREMENT,
DEFAULT,
UNIQUE

/* TIPOS DE DADOS */
BOOLEAN
TEXT, CHAR(0), VARCHAR(00)
SERIAL, INT, FLOAT
DATE, TIME, TIMESTAMP, TIMESTAMPTZ
ARRAY
MONEY
BYTEA

/* psql -U postgres */
CREATE DATABASE testdb;
\c testdb
CREATE TABLE usuarios(
    id SERIAL NOT NULL PRIMARY KEY, 
    nome VARCHAR(32) NOT NULL UNIQUE,
    email VARCHAR(64) NOT NULL UNIQUE,
    senha VARCHAR(16) NOT NULL,
    registrado_em DATE NOT NULL DEFAULT CURRENT_DATE
);
