/* INSERINDO DADOS */
INSERT INTO usuarios VALUES('Pedro', '1234');
INSERT INTO usuarios VALUES('Duda', '4321');
INSERT INTO usuarios VALUES('Cristina', '7896');
INSERT INTO usuarios VALUES('Luiz', '4561');

/* SELECIONANDO DADOS */
SELECT * FROM usuarios;

/* SELECIONANDO DADOS COM CONDIÇÃO */
SELECT * FROM usuarios WHERE nome = 'Pedro';
SELECT * FROM usuarios WHERE id > 3;

/* SELECIONANDO DADOS COM ORDENAÇÃO */
SELECT * FROM usuarios ORDER BY nome ASC;
SELECT * FROM usuarios ORDER BY id DESC;

/* SELECIONANDO DADOS COM LIMITE */
SELECT * FROM usuarios LIMIT 5;

/* SELECIONANDO OS PRIMEIROS DADOS */
SELECT TOP 3 * FROM usuarios;

/* SELECIONANDO OS DADOS COM PARAMETROS */
SELECT * FROM usuarios WHERE nome LIKE 'p%';